apiVersion: apps/v1
kind: Deployment
metadata:
  name: afs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: afs
  template:
    metadata:
      labels:
        app: afs
    spec:
      containers:
      - name: afs
        image: adiaby2609/afs:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
